name: Publish to IPFS

on:
  push:
    branches: [ gh-pages ]
  workflow_dispatch:

jobs:
  push_to_ipfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aquiladev/ipfs-action@v1
        with:
          path: ./build
          service: pinata
          pinataKey: ${{ secrets.PINATA_KEY }}
          pinataSecret: ${{ secrets.PINATA_SECRET }}
          pinataPinName: Blog
