name: Build and deploy to GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AndreiChenchik/jekyll-action@v2.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: "gh-pages"
      - uses: anantaramdas/ipfs-pinata-deploy-action@v1.6.4
        id: push_to_ipfs
        with:
          pin-name: Blog
          path: ./build
          pinata-api-key: ${{ secrets.PINATA_KEY }}
          pinata-secret-api-key: ${{ secrets.PINATA_SECRET }}
          verbose: false
          remove-old: true
      - name: Update DNSLink for main
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          RECORD_DOMAIN: "chenchik.me"
          RECORD_NAME: "_dnslink.ipfs.chenchik.me"
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        id: dnslink
        uses: textileio/cloudflare-update-dnslink@master
        with:
          cid: ${{ steps.push.outputs.cid }}
      - name: Update DNSLink for ipfs
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          RECORD_DOMAIN: "chenchik.me"
          RECORD_NAME: "_dnslink.chenchik.me"
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        id: dnslink2
        uses: textileio/cloudflare-update-dnslink@master
        with:
          cid: ${{ join(steps.push_to_ipfs.outputs.*) }}
