name: Build and deploy to GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AndreiChenchik/jekyll-action@v2.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: "gh-pages"
